version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ctgeo
    ports:
      - 8083:80
  db:
    image: mysql:8.0.17
    container_name: mysql_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: nodesir
      MYSQL_PASSWORD: nodesir
      MYSQL_DATABASE: develop
    ports:
      - '3306:3306'
  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - db
    ports:
      - '8082:8080'

volumes:
  db_data:
